// Generated by CoffeeScript 1.6.3
var cover, fs;

cover = require('../isbn-cover');

fs = require('fs');

cover(440234816, function(img) {
  console.log(img);
  return fs.writeFileSync('test.jpg', img);
});

test.done();
